// SCHEMA LOADER - MODULE ORGANIZATION
// Dy's Sunflower Suite v5.0
// Loads and combines schema files from multiple modules

const fs = require('fs');
const path = require('path');

class SchemaLoader {
  /**
   * Loads all module schemas from separate files and combines them
   * @returns Combined schemas ready for database initialization
   */
  static loadSchemas() {
    // CRITICAL: SQL files are NOT copied during TypeScript compilation
    // We must load from source directory, not dist-electron
    // __dirname in compiled code points to dist-electron/database/
    // We need to go back to the source: electron/database/schemas/
    const schemasDir = path.join(__dirname, '..', '..', 'electron', 'database', 'schemas');
    
    console.log('📁 Loading schemas from:', schemasDir);
    
    try {
      // Load individual schema files
      const moduleA = fs.readFileSync(path.join(schemasDir, 'module-a.sql'), 'utf8');
      const moduleB = fs.readFileSync(path.join(schemasDir, 'module-b.sql'), 'utf8');
      const moduleC = fs.readFileSync(path.join(schemasDir, 'module-c.sql'), 'utf8');
      const moduleSU = fs.readFileSync(path.join(schemasDir, 'module-su.sql'), 'utf8');
      
      // Validate schemas loaded correctly
      if (!moduleA.includes('CREATE TABLE')) {
        throw new Error('Module A schema appears to be empty or invalid');
      }
      
      if (!moduleB.includes('CREATE TABLE')) {
        throw new Error('Module B schema appears to be empty or invalid');
      }
      
      if (!moduleC.includes('CREATE TABLE')) {
        throw new Error('Module C schema appears to be empty or invalid');
      }
      
      // Module SU can be empty (placeholder file)
      
      // Combine schemas in dependency order (Module A first, then B, then C, then SU)
      const combined = [
        '-- COMBINED SCHEMA - ALL MODULES',
        '-- Generated by SchemaLoader at ' + new Date().toISOString(),
        '',
        moduleA,
        '',
        moduleB,
        '',
        moduleC,
        '',
        moduleSU
      ].join('\n');
      
      console.log('✅ Schemas loaded successfully:');
      console.log(`   - Module A: ${moduleA.length} characters`);
      console.log(`   - Module B: ${moduleB.length} characters`);
      console.log(`   - Module C: ${moduleC.length} characters`);
      console.log(`   - Module SU: ${moduleSU.length} characters`);
      console.log(`   - Combined: ${combined.length} characters`);
      
      return { 
        moduleA, 
        moduleB, 
        moduleC,
        moduleSU, 
        combined 
      };
      
    } catch (error) {
      console.error('❌ Failed to load schema files:', error.message);
      console.error('   Schemas directory:', schemasDir);
      
      // Check which files exist for debugging
      try {
        const files = fs.readdirSync(schemasDir);
        console.error('   Available files:', files);
      } catch (dirError) {
        console.error('   Could not read schemas directory');
      }
      
      throw new Error(`Schema loading failed: ${error.message}`);
    }
  }
  
  /**
   * Validates that all required schema files exist
   * @returns true if all files exist, false otherwise
   */
  static validateSchemaFiles() {
    const schemasDir = path.join(__dirname, '..', '..', 'electron', 'database', 'schemas');
    const requiredFiles = ['module-a.sql', 'module-b.sql', 'module-c.sql', 'module-su.sql'];
    
    try {
      for (const file of requiredFiles) {
        const filePath = path.join(schemasDir, file);
        if (!fs.existsSync(filePath)) {
          console.error(`❌ Missing schema file: ${file}`);
          return false;
        }
      }
      
      console.log('✅ All schema files found');
      return true;
      
    } catch (error) {
      console.error('❌ Error validating schema files:', error.message);
      return false;
    }
  }
}

module.exports = { SchemaLoader };
